export const events = [
  {
    id: 1,
    title: "React Conf 2025",
    image: "/images/event1.png",
    slug: "react-conf-2025",
    date: "March 15-16, 2025",
    location: "San Francisco, CA",
    time: "9:00 AM - 6:00 PM",
  },
  {
    id: 2,
    title: "Next.js Conference",
    image: "/images/event2.png",
    slug: "nextjs-conference-2025",
    date: "April 10-11, 2025",
    location: "New York, NY",
    time: "10:00 AM - 5:00 PM",
  },
  {
    id: 3,
    title: "DevHack 2025",
    image: "/images/event3.png",
    slug: "devhack-2025",
    date: "May 3-5, 2025",
    location: "Austin, TX",
    time: "24/7 Hackathon",
  },
  {
    id: 4,
    title: "AWS Summit 2025",
    image: "/images/event4.png",
    slug: "aws-summit-2025",
    date: "June 12-13, 2025",
    location: "Seattle, WA",
    time: "8:00 AM - 7:00 PM",
  },
  {
    id: 5,
    title: "JavaScript Meetup",
    image: "/images/event5.png",
    slug: "javascript-meetup-2025",
    date: "February 28, 2025",
    location: "Boston, MA",
    time: "6:00 PM - 9:00 PM",
  },
  {
    id: 6,
    title: "TechCrunch Disrupt",
    image: "/images/event6.png",
    slug: "techcrunch-disrupt-2025",
    date: "September 18-20, 2025",
    location: "San Francisco, CA",
    time: "9:00 AM - 6:00 PM",
  },
  {
    id: 7,
    title: "PyData Global 2025",
    image: "/images/event1.png",
    slug: "pydata-global-2025",
    date: "July 8-10, 2025",
    location: "London, UK",
    time: "9:00 AM - 6:00 PM",
  },
  {
    id: 8,
    title: "NodeConf EU",
    image: "/images/event2.png",
    slug: "nodeconf-eu-2025",
    date: "October 15-17, 2025",
    location: "Dublin, Ireland",
    time: "10:00 AM - 5:00 PM",
  },
  {
    id: 9,
    title: "DevOps World",
    image: "/images/event3.png",
    slug: "devops-world-2025",
    date: "August 5-7, 2025",
    location: "Las Vegas, NV",
    time: "8:00 AM - 7:00 PM",
  },
  {
    id: 10,
    title: "AI & Machine Learning Summit",
    image: "/images/event4.png",
    slug: "ai-ml-summit-2025",
    date: "November 12-14, 2025",
    location: "Toronto, Canada",
    time: "9:00 AM - 6:00 PM",
  },
];

